Refactor JSON Parsing to Use Boost.JSON (#202)
* boost json parser

Signed-off-by: Charity Kathure <ckathure@microsoft.com>

Co-authored-by: Charity Kathure <ckathure@microsoft.com>

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,84 +2,149 @@ trigger:
 - main
 
 pool:
-    vmImage: 'windows-2022'  # name of the pool to run this job in
-    demands: 
-      - msbuild
-      - visualstudio
-      - vstest
+  vmImage: 'windows-2022'
+  demands:
+    - msbuild
+    - visualstudio
+    - vstest
 
 variables:
   solution: '**/*.sln'
-  buildPlatform: 'x86|x64|ARM'
+  buildPlatform: 'x64'  # Set to x64 or ARM64 depending on the build you want
   buildConfiguration: 'Release'
+  VCPKG_ROOT: '$(Build.SourcesDirectory)\vcpkg'
+  VCPKG_CMAKE_OPTIONS: '-DCMAKE_TOOLCHAIN_FILE=$(VCPKG_ROOT)\scripts\buildsystems\vcpkg.cmake'
+  SDKVersion: ''
 
 jobs:
-  - job: x64_build
+  - job: build
     steps:
-    - task: VSBuild@1
-      inputs:
-        platform: 'x64'
-        solution: '$(solution)'
-        configuration: '$(buildConfiguration)'
-
-    - task: ComponentGovernanceComponentDetection@0
-      inputs:
-        scanType: 'Register'
-        verbosity: 'Verbose'
-        alertWarningLevel: 'Low'
-
-    - task: VisualStudioTestPlatformInstaller@1
-      inputs:
-        packageFeedSelector: 'nugetOrg'
-        versionSelector: 'latestPreRelease'
-
-    - task: VSTest@2
-      inputs:
-        testSelector: 'testAssemblies'
-        testAssemblyVer2: '**\*test*.dll'
-        searchFolder: '$(System.DefaultWorkingDirectory)' 
-        runOnlyImpactedTests: false
-        runInParallel: false
-        rerunFailedTests: true
-        rerunMaxAttempts: 3
-    
-    - task: PublishPipelineArtifact@1
-      inputs:
-        targetPath: '$(Build.SourcesDirectory)\LogMonitor\x64\Release\'
-        artifactType: 'pipeline'
-        artifactName: '64-bit'
-    
-  - job: x86_build
-    steps:
-      - task: VSBuild@1
+      - task: PowerShell@2
+        displayName: 'Install vcpkg'
         inputs:
-          platform: 'x86'
-          solution: '$(solution)'
-          configuration: '$(buildConfiguration)'
+          targetType: 'inline'
+          script: |
+            echo "Cloning and bootstrapping vcpkg"
+            git clone https://github.com/microsoft/vcpkg.git $(VCPKG_ROOT)
+            cd $(VCPKG_ROOT)
+            .\bootstrap-vcpkg.bat
+            .\vcpkg.exe integrate install  # Integrate vcpkg with MSBuild
 
+      # Install Boost JSON for the selected platform (x64 or ARM64)
+      - task: PowerShell@2
+        displayName: 'Install Boost JSON'
+        inputs:
+          targetType: 'inline'
+          script: |
+            if (!(Test-Path "$(VCPKG_ROOT)\vcpkg.exe")) {
+                Write-Error "vcpkg.exe not found. Exiting..."
+                exit 1
+            }
+            Write-Host "Installing Boost JSON for platform: $(buildPlatform)..."
+            if ('$(buildPlatform)' -eq 'x64') {
+              & "$(VCPKG_ROOT)\vcpkg.exe" install boost-json:x64-windows
+            } elseif ('$(buildPlatform)' -eq 'ARM64') {
+              & "$(VCPKG_ROOT)\vcpkg.exe" install boost-json:arm64-windows
+            } else {
+              Write-Error "Unsupported build platform: $(buildPlatform)"
+              exit 1
+            }
+
+      # Verify vcpkg integration
+      - task: PowerShell@2
+        displayName: 'Verify vcpkg Integration'
+        inputs:
+          targetType: 'inline'
+          script: |
+            echo "Verifying vcpkg integration for platform: $(buildPlatform)..."
+            & "$(VCPKG_ROOT)\vcpkg.exe" integrate install
+            if ('$(buildPlatform)' -eq 'x64') {
+                if (!(Test-Path "$(VCPKG_ROOT)\installed\x64-windows\include\boost\json.hpp")) {
+                    Write-Error "Boost JSON header not found for x64. Exiting..."
+                    exit 1
+                }
+            } elseif ('$(buildPlatform)' -eq 'ARM64') {
+                if (!(Test-Path "$(VCPKG_ROOT)\installed\arm64-windows\include\boost\json.hpp")) {
+                    Write-Error "Boost JSON header not found for ARM64. Exiting..."
+                    exit 1
+                }
+            }
+            Write-Output "vcpkg integration verified."
+
+      # Get installed Windows SDK version
+      - task: PowerShell@2
+        displayName: 'Check Installed Windows SDK Version'
+        inputs:
+          targetType: 'inline'
+          script: |
+            $x86SdkPath = "C:\Program Files (x86)\Windows Kits\10\Include"
+            $x64SdkPath = "C:\Program Files\Windows Kits\10\Include"
+            $armSdkPath = "C:\Program Files\Windows Kits\10\Include\arm64"
+
+            function Get-SdkVersion {
+                param ($sdkPath)
+                $sdkVersion = Get-ChildItem $sdkPath | Where-Object { $_.PSIsContainer -and $_.Name -match '^\d+\.\d+' } | Sort-Object -Property Name | Select-Object -Last 1
+                return $sdkVersion
+            }
+
+            $sdkFolder = $null
+            if (Test-Path $x64SdkPath) {
+                $sdkFolder = Get-SdkVersion -sdkPath $x64SdkPath
+            } elseif (Test-Path $x86SdkPath) {
+                $sdkFolder = Get-SdkVersion -sdkPath $x86SdkPath
+            } elseif (Test-Path $armSdkPath) {
+                $sdkFolder = Get-SdkVersion -sdkPath $armSdkPath
+            }
+            
+            if ($sdkFolder) {
+                Write-Host "Installed Windows SDK version: $($sdkFolder.Name)"
+                Write-Host "##vso[task.setvariable variable=SDKVersion]$($sdkFolder.Name)"
+            } else {
+                Write-Host "Windows SDK not found!"
+                exit 1
+            }
+
+      # Configure CMake based on selected platform
+      - task: CMake@1
+        displayName: 'Configure CMake'
+        inputs:
+          workingDirectory: '$(Build.SourcesDirectory)\LogMonitor'
+          cmakeArgs: |
+            -A $(buildPlatform) -S $(Build.SourcesDirectory)\LogMonitor -B $(Build.BinariesDirectory)\LogMonitor\$(buildPlatform)
+
+      - task: CMake@1
+        displayName: 'Build with CMake'
+        inputs:
+          workingDirectory: '$(Build.BinariesDirectory)\LogMonitor\$(buildPlatform)'
+          cmakeArgs: '--build . --config $(buildConfiguration) --parallel'
+
+      # Component Governance
       - task: ComponentGovernanceComponentDetection@0
         inputs:
-          scanType: 'LogOnly'
+          scanType: 'Register'
           verbosity: 'Verbose'
-          alertWarningLevel: 'High'
+          alertWarningLevel: 'Low'
 
+      # Install Visual Studio Test Platform
       - task: VisualStudioTestPlatformInstaller@1
         inputs:
           packageFeedSelector: 'nugetOrg'
           versionSelector: 'latestPreRelease'
 
+      # Run Tests
       - task: VSTest@2
         inputs:
           testSelector: 'testAssemblies'
           testAssemblyVer2: '**\*test*.dll'
-          searchFolder: '$(System.DefaultWorkingDirectory)' 
+          searchFolder: '$(Build.BinariesDirectory)\LogMonitor\$(buildPlatform)\$(buildConfiguration)\'
           runOnlyImpactedTests: false
           runInParallel: false
           rerunFailedTests: true
           rerunMaxAttempts: 3
-      
+
+      # Publish build artifacts
       - task: PublishPipelineArtifact@1
         inputs:
-          targetPath: '$(Build.SourcesDirectory)\LogMonitor\Release\'
+          targetPath: '$(Build.BinariesDirectory)\LogMonitor\$(buildPlatform)\$(buildConfiguration)\'
           artifactType: 'pipeline'
-          artifactName: '32-bit'
+          artifactName: '$(buildPlatform)-$(buildConfiguration)'
